---
- name: Deploy Pihole to UDM
  hosts: udm
  remote_user: root

  tasks:
  - name: Pull Latest Docker Image
    delegate_to: localhost
    docker_image:
      docker_host: "ssh://{{ hostvars[inventory_hostname].ansible_host }}"
      name: "pihole/pihole"
    ignore_errors: yes

  - name: Deploy Pihole1
    delegate_to: localhost
    docker_container:
      docker_host: "ssh://{{ hostvars[inventory_hostname].ansible_host }}"
      name: pihole1
      image: pihole/pihole
      state: started
      restart_policy: always
      env_file: .env
      hostname: pihole1
      volumes:
      - pihole1-etc:/etc/pihole
      networks:
      - name: "services"
        ipv4_address: 192.168.3.11
      ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      capabilities:
      - NET_ADMIN

  - name: Deploy Pihole2
    delegate_to: localhost
    docker_container:
      docker_host: "ssh://{{ hostvars[inventory_hostname].ansible_host }}"
      name: pihole2
      image: pihole/pihole
      state: started
      restart_policy: always
      env_file: .env
      hostname: pihole2
      volumes:
      - pihole2-etc:/etc/pihole
      networks:
      - name: "services"
        ipv4_address: 192.168.3.12
      ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      capabilities:
      - NET_ADMIN
