---
- name: Install Docker to UDM
  hosts: udm
  remote_user: root

  tasks:
  - name: Install Docker Dependencies
    apt:
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: Add Docker Apt Repository Key
    ansible.builtin.apt_key:
      state: present
      url: https://download.docker.com/linux/debian/gpg

  - name: Add Docker Apt Repository
    ansible.builtin.apt_repository:
      state: present
      filename: docker
      repo: deb [arch=arm64] https://download.docker.com/linux/debian stretch stable

  - name: Install Docker
    apt:
      update_cache: yes
      state: latest
      pkg:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
