---
- name: Configure Linux Systemd Networking to allow for MACVLAN Containers (to avoid port collisions with host)
  hosts: udm
  remote_user: root

  tasks:
  - name: Create systemd-network conf files.
    copy:
      src: "{{ item }}"
      dest: "/etc/systemd/network/{{ item | basename }}"
    with_fileglob: "network-files/*"
    register: network_files

  - name: Restart network
    service:
      name: systemd-networkd
      state: restarted
    when: network_files.changed

  - name: Wait for network to restart
    wait_for_connection:
      delay: 60
      timeout: 300
